### ISSUE TITLE
juiste parameters vinden voor geen overflow error

### ISSUE THREAD

**Issue by SampersS** [vives-project-xp/DancingLight#132]
**Describe the Issue**
de error is als volgd:
Traceback (most recent call last):
  File "/home/elias/h.py", line 30, in <module>
    audio_data = np.frombuffer(stream.read(chunk_size), dtype=np.int16)
  File "/usr/lib/python3/dist-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9981] Input overflowed

**Additional context**

**Comment by SampersS** [comment]
dit script is nu zelfredzaam
